### ISSUE TITLE
Update reference code for schema change

### ISSUE THREAD

**Issue by kellrott** [bmeg/task-execution-server#17]
Parameter names have changed in https://github.com/bmeg/task-execution-schemas/pull/1
Reference code needs to be updated

**Comment by jeenalee** [comment]
This is running `protoc-gen-go` to create `.pb.go`, right? Do I add the new `task_execution.pb.go` to `src/ga4gh-tasks/`?

**Comment by kellrott** [comment]
The procedure should be: after updating the `task-execution-schema` submodule (`cd task-execution-schemas && git checkout master && git pull`) re-run `make proto_build`.

**Comment by jeenalee** [comment]
Fixed in #19.
