### ISSUE TITLE
Allow tes worker to accept swift and non-swift jobs at the same time

### ISSUE THREAD

**Issue by malisas** [bmeg/task-execution-server#21]
Currently, the
`./bin/tes-worker --master 127.0.0.1:9090 --swift cache_dir`
command tells the worker to interpret input location (supplied in the posted protobuf-JSON) as a swift object store file. If you don't include the swift argument, it's interpreted as a local file. We should:

1) Allow a single running worker to accept a swift job, followed by a non-swift job.
2) Consider allowing a single running worker to accept a job which uses both swift and a local file.

**Comment by buchanae** [comment]
The architecture is in place now (via #42) for this. There are some fixes that need to be made to make the storage configuration more flexible and job-specific, but I'll file new, specific issues for those things soon.
