### ISSUE TITLE
Possible data race in Worker code

### ISSUE THREAD

**Issue by malisas** [bmeg/task-execution-server#23]
We (mostly @jeenalee ) discovered a possible data race in the files [worker.go](https://github.com/bmeg/task-execution-server/blob/0f4591bee4613d57c0c92c2a5fe949b609b6702b/src/tes-worker/worker.go#L70) and [fork_engine.go](https://github.com/bmeg/task-execution-server/blob/0f4591bee4613d57c0c92c2a5fe949b609b6702b/src/tes/worker/fork_engine.go#L87).

In `worker.go`, `manager.SetStatusCheck()` takes a func() argument which gets assigned internally within manager to the `checkFunc` field. This function accesses `lastPing` in `worker.go`.

`worker.go` calls `manager.Start()` a few lines later. `manager.Start()` spawns a new thread, from which `checkFunc` is called. 

Near the end of `worker.go`, `lastPing` is read using the original thread. This means that one thread is reading `lastPing` while another is writing to `lastPing` concurrently. We believe this results in a data race.

We might want to consider using synchronization tools here, such as a lock, a channel, or atomic.

**Comment by jeenalee** [comment]
`manager.Start()` has to create a new thread, so making it not spawn a new thread would not fix this issue.

Similarly, grpc related function calls such as [`UpdateJobStatus`](https://github.com/bmeg/task-execution-server/blob/develop/src/tes/worker/fork_engine.go#L33) should be refactored to avoid data race.

**Comment by buchanae** [comment]
Should be fixed by #38 Would love your review there to see if you agree.

**Comment by buchanae** [comment]
The worker rewrite should have fixed this. I'm not sure it's possible or worth the effort to write a unit test proving this. Closing.
