### ISSUE TITLE
Minio Client?

### ISSUE THREAD

**Issue by kellrott** [bmeg/task-execution-server#34]
Maybe switch from OpenStack swift client to https://github.com/minio/minio-go
It reports compatibility with:
- Amazon S3
- Minio
- Google Cloud Storage (Compatibility Mode)
- Openstack Swift + Swift3 middleware
- Ceph Object Gateway
- Riak CS

**Comment by buchanae** [comment]
Minio is being experimented with now on the `develop` branch.
