### ISSUE TITLE
Add `.github/` to `bmeg:master` so that we can use the pull request template

### ISSUE THREAD

**Issue by jeenalee** [bmeg/task-execution-server#6]
If we want to start using the template, `.github/` has to be in the default branch, which is the master branch. Currently `.github/` is present in `bmeg:develop` but not in `bmeg:master`.

**Comment by kellrott** [comment]
It should be merged to master now

**Comment by jeenalee** [comment]
[Fixed](https://github.com/bmeg/task-execution-server/commit/5e861a660778ab995caa918c7742a19f9fffebf5).
