### ISSUE TITLE
Add documentation to `docker.go`, `engine.go` and related files

### ISSUE THREAD

**Issue by jeenalee** [bmeg/task-execution-server#9]
Yesterday, @prismofeverything @malisas and I figured out the roles of functions and types in `src/tes/worker/docker.go` and `src/tes/worker/engine.go`.

I am working on adding comments and documentation to these files.

**Comment by buchanae** [comment]
There is documentation for all exported methods now.

**Comment by buchanae** [comment]
Oh sorry, I guess I should wait until the PR is merged, https://github.com/bmeg/task-execution-server/pull/61
